"""Asynchronous receipt processing.

A real receipt can carry 400K+ entries; ingesting it inside one HTTP
request times out at every proxy on the way. So: the upload endpoint
stores the raw bytes, creates a job row, and returns immediately; a
background thread parses (gzip-aware), validates, and inserts in batches,
updating the job row the UI polls.

Idempotency guarantees (retries after partial failure are SAFE):
- one completed non-dry job per manifest_id — later uploads short-circuit
- quarantine_item unique on (manifest_id, original_path): ON CONFLICT skip
- execution unique on (decision_id, manifest_ref): reused, not duplicated
"""
import gzip
import json
import pathlib
import threading
import traceback

from app.housekeeping import db as hk
from app.housekeeping import manifests as mf

RECEIPT_DIR = pathlib.Path("/backups/receipts")
BATCH = 5000


def start_job(raw: bytes, actor: str) -> dict:
    """Store the upload, register the job, kick off processing. Fast."""
    if raw[:2] == b"\x1f\x8b":
        text = gzip.decompress(raw).decode("utf-8")
    else:
        text = raw.decode("utf-8")
    try:
        receipt = json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(f"not valid JSON (line {e.lineno}): expected the executor's receipt") from e

    problems = mf.validate_receipt(receipt)
    if problems:
        raise ValueError("; ".join(problems))
    manifest_id = receipt["manifest_id"]
    if mf.load_manifest(manifest_id) is None:
        raise ValueError(f"unknown manifest {manifest_id!r} — was it generated by this dashboard?")

    total = len(receipt.get("outcomes", [])) + len(receipt.get("succeeded_paths", []))
    dry = bool(receipt.get("dry_run"))

    with hk.tx() as conn:
        done = conn.execute(
            "SELECT id, execution_ids FROM hk_receipt_job"
            " WHERE manifest_id = %s AND status = 'done' AND NOT dry_run LIMIT 1",
            (manifest_id,)).fetchone()
        if done and not dry:
            row = conn.execute(
                "INSERT INTO hk_receipt_job (manifest_id, status, processed, total, dry_run,"
                " note, execution_ids, created_by, finished_at)"
                " VALUES (%s, 'done', %s, %s, %s, %s, %s, %s, now()) RETURNING id",
                (manifest_id, total, total, dry,
                 f"already processed by job #{done[0]} — nothing re-counted",
                 done[1], actor)).fetchone()
            return {"job_id": row[0], "already_processed": True}
        row = conn.execute(
            "INSERT INTO hk_receipt_job (manifest_id, total, dry_run, created_by)"
            " VALUES (%s, %s, %s, %s) RETURNING id",
            (manifest_id, total, dry, actor)).fetchone()
        job_id = row[0]

    RECEIPT_DIR.mkdir(parents=True, exist_ok=True)
    (RECEIPT_DIR / f"job-{job_id}.receipt.json.gz").write_bytes(
        gzip.compress(text.encode("utf-8")))

    t = threading.Thread(target=_process, args=(job_id, receipt, actor), daemon=True)
    t.start()
    return {"job_id": job_id, "already_processed": False}


def _set(job_id: int, **fields):
    cols = ", ".join(f"{k} = %s" for k in fields)
    with hk.tx() as conn:
        conn.execute(f"UPDATE hk_receipt_job SET {cols} WHERE id = %s",
                     (*fields.values(), job_id))


def _process(job_id: int, receipt: dict, actor: str) -> None:
    try:
        _set(job_id, status="validating")
        manifest = mf.load_manifest(receipt["manifest_id"])
        exec_ids: list[int] = []
        processed = 0

        if not receipt.get("dry_run"):
            _set(job_id, status="processing")
            with hk.tx() as conn:
                executor = str(receipt["executor"]).lower()
                conn.execute("INSERT INTO person (username) VALUES (%s) ON CONFLICT DO NOTHING",
                             (executor,))
                for decision_id in manifest["decision_ids"]:
                    row = conn.execute(
                        "INSERT INTO execution (decision_id, executor, owner_uname, manifest_ref,"
                        " destination_path) VALUES (%s, %s, %s, %s, %s)"
                        " ON CONFLICT (decision_id, manifest_ref) DO UPDATE SET executor = EXCLUDED.executor"
                        " RETURNING id",
                        (decision_id, executor, manifest["owner_uname"], manifest["manifest_id"],
                         manifest["quarantine_dir"] if receipt["action"] == "quarantine" else None),
                    ).fetchone()
                    exec_ids.append(row[0])

            # Quarantine registry, batched. Successes come from the compact
            # succeeded_paths (new receipts) or full outcomes (old receipts).
            if receipt["action"] == "quarantine" and exec_ids:
                quarantined = list(receipt.get("succeeded_paths", []))
                quarantined += [o["path"] for o in receipt.get("outcomes", [])
                                if o.get("outcome") == "quarantined"]
                size_by_path = {e["path"]: e["size_bytes"] for e in manifest.get("entries", [])}
                root, qdir = manifest["root"], manifest["quarantine_dir"]
                for i in range(0, len(quarantined), BATCH):
                    chunk = quarantined[i:i + BATCH]
                    rows = [
                        (exec_ids[0], manifest["manifest_id"], p,
                         qdir + p[len(root):], size_by_path.get(p, 0))
                        for p in chunk
                    ]
                    with hk.tx() as conn:
                        conn.cursor().executemany(
                            "INSERT INTO quarantine_item (execution_id, manifest_id,"
                            " original_path, quarantine_path, size_bytes, expires_at)"
                            " VALUES (%s, %s, %s, %s, %s, now() + interval '30 days')"
                            " ON CONFLICT (manifest_id, original_path) DO NOTHING",
                            rows)
                    processed += len(chunk)
                    _set(job_id, processed=processed)

        with hk.tx() as conn:
            hk.write_with_event(
                conn, actor, "receipt_uploaded",
                target_id=manifest["target_ids"][0] if manifest.get("target_ids") else None,
                ref_table="hk_receipt_job", ref_id=job_id,
                payload={
                    "manifest_id": manifest["manifest_id"],
                    "action": receipt["action"],
                    "dry_run": bool(receipt.get("dry_run")),
                    "bytes_freed": receipt.get("bytes_freed", 0),
                    "files_removed": receipt.get("files_removed", 0),
                    "files_skipped_changed": receipt.get("files_skipped_changed", 0),
                    "files_skipped_no_access": receipt.get("files_skipped_no_access", 0),
                    "files_failed": receipt.get("files_failed", 0),
                    "execution_ids": exec_ids,
                })
        _set(job_id, status="done", processed=processed, execution_ids=exec_ids,
             finished_at=__import__("datetime").datetime.now(__import__("datetime").timezone.utc))
    except Exception as e:
        traceback.print_exc()
        _set(job_id, status="failed",
             error=f"{type(e).__name__}: {e} (after {locals().get('processed', 0)} rows —"
                   " re-uploading the same receipt is safe and will not double-count)")


def job_status(job_id: int) -> dict | None:
    with hk.tx() as conn:
        r = conn.execute(
            "SELECT id, manifest_id, status, processed, total, dry_run, error, note,"
            " execution_ids, created_at, finished_at FROM hk_receipt_job WHERE id = %s",
            (job_id,)).fetchone()
    if not r:
        return None
    return {"job_id": r[0], "manifest_id": r[1], "status": r[2], "processed": r[3],
            "total": r[4], "dry_run": r[5], "error": r[6], "note": r[7],
            "execution_ids": r[8], "created_at": str(r[9]),
            "finished_at": str(r[10]) if r[10] else None}
